---
- name: Jenkins
  hosts: localhost
  connection: local
  tasks:
    - name: Create an EC2 Instance for Jenkins
      ec2:
        region: us-west-2
        group_id: sg-56979f2e
        image: ami-a58d0dc5
        instance_type: t2.micro
        wait: yes
        count_tag: env
        exact_count: 1
        instance_tags:
          Name: JenkinAssignment
      register: ec2